language: c
sudo: required
install:
    - sudo apt-get install --yes build-essential
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - sudo apt-get update --yes -q
    - sudo apt-get install --yes gcc-5
    - sudo rm  -f /usr/bin/gcc
    - sudo ln -s /usr/bin/gcc-5 /usr/bin/gcc
script:
    - cd ./PK/build/
    - ./build.sh
    - cd ../..
    - cd ./main/build/
    - ./build.sh
