language: c
sudo: required
install:
    - CURRENTDIR=$(PWD)
    - sudo apt-get install --yes build-essential
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - sudo apt-get update --yes -q
    - sudo apt-get install --yes gcc-5
    - cd /usr/bin
    - sudo rm  -f gcc
    - sudo ln -s gcc-5 gcc
    - cd CURRENTDIR
script:
    - cd ./PK/build/
    - ./build.sh
    - cd ../..
    - cd ./main/build/
    - ./build.sh
