language: c
sudo: required
install:
    - sudo apt-get install --yes build-essential
    - sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test
    - sudo apt-get update --yes
    - sudo apt-get install --yes gcc-5.1 g++-5.1 cpp-5.1
    - cd /usr/bin
    - sudo rm  -f gcc g++ cpp
    - sudo ln -s gcc-5.1 gcc
    - sudo ln -s g++-5.1 g++
    - sudo ln -s cpp-5.1 cpp
script:
    - cd ./PK/build/
    - ./build.sh
    - cd ../..
    - cd ./main/build/
    - ./build.sh
