language: c
sudo: required
cache:
  directories:
    - $HOME/nim
before_install:
    -  |
        sudo apt-get install --yes build-essential
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
        sudo apt-get update -q
        sudo apt-get install --yes gcc-5 libzip-dev
        sudo rm  -f /usr/bin/gcc
        sudo ln -s /usr/bin/gcc-5 /usr/bin/gcc
before_script:
    - |
        if [ ! -x "$HOME/nim/bin/nim" ]; then
          git clone -b devel --depth 1 git://github.com/araq/nim "$HOME/nim/"
          cd "$HOME/nim/"
          ./build.sh
          rm -rf csources
        else
          cd "$HOME/nim"; git fetch origin
          git merge FETCH_HEAD | grep "Already up-to-date" || (bin/nim c koch; ./koch boot -d:release)
        fi
script:
    - |
        cd "$TRAVIS_BUILD_DIR"
        export PATH="$PATH:$HOME/nim/bin/"
    - |
        nim c main
        nim c -d:release main
    - |
        nim c PK
        nim c -d:release PK