language: c
sudo: required
install:
    - sudo apt-get install build-essential
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test
    - sudo apt-get update
    - sudo apt-get install gcc-4.8 g++-4.8 cpp-4.8
    - cd /usr/bin
    - sudo rm gcc g++ cpp
    - sudo ln -s gcc-4.8 gcc
    - sudo ln -s g++-4.8 g++
    - sudo ln -s cpp-4.8 cpp
script:
    - cd ./PK/build/
    - ./build.sh
    - cd ../..
    - cd ./main/build/
    - ./build.sh
