version: 1.0.{build}
os: MinGW
clone_folder: c:\5PK
environment:
  PATH: C:\MINGW\bin\;C:\Nim\bin\;%PATH%
install:
- cd C:\
- git clone -b devel -q --depth 1 https://github.com/nim-lang/Nim.git Nim
- cd Nim
- git clone --depth 1 -q git://github.com/nim-lang/csources.git csources
- cd csources
- .\build.bat
- cd C:\Nim
- nim c koch
- .\koch.exe boot -d:release
build_script:
- cd C:\5PK
- nim c --threads=on main
- nim c --threads=on -d:release main
- nim c start
- nim c -d:release start
test_script:
- nim c --threads=on -r demo
- nim c --threads=on -d:release -r demo
after_build:
- 7z a 5_PK.zip main.exe start.exe
- appveyor PushArtifact 5_PK.zip
