version: 1.0.{build}
os: MinGW
shallow_clone: true
clone_depth: 1
clone_folder: c:\5PK
environment:
  PATH: C:\MINGW\bin\;C:\Nim\bin\;%PATH%
install:
- cd C:\
- git clone -b devel -q --depth 1 --recursive https://github.com/Araq/Nim.git Nim
- cd Nim\csources
- .\build.bat
- cd C:\Nim
- nim c koch
- .\koch.exe boot -d:release
build_script:
- cd C:\5PK
- nim c main
- nim c -d:release main
- nim c PK
- nim c -d:release PK
- nim c -r demo
- RD /S /Q testData
- nim c -d:release -r demo
after_build:
- 7z a 5_PK.zip main.exe PK.exe
- appveyor PushArtifact 5_PK.zip
